### ISSUE TITLE
java.lang.IllegalArgumentException: permission is null

### ISSUE THREAD

**Issue by psnehanshu** [NathanaelA/nativescript-permissions#30]
When I try `permissions.hasPermission`, this error happens
<pre>
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onClick failed

Error: java.lang.IllegalArgumentException: permission is null
    android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:450)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:12)
    android.view.View.performClick(View.java:5205)
    android.view.View$PerformClick.run(View.java:21164)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "file:///data/data/org.nativescript.Browse/files/app/tns_modules/nativescript-permissions/permissions.js, line: 112, column: 43

StackTrace: 
	Frame: function:'hasPermission', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/nativescript-permissions/permissions.js', line: 112, column: 44
	Frame: function:'flash', file:'file:///data/data/org.nativescript.Browse/files/app/page2.js', line: 10, column: 21
	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
	Frame: function:'Observable._emit', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 127, column: 18
	Frame: function:'ClickListenerImpl.onClick', file:'file:///data/data/org.nativescript.Browse/files/app/tns_modules/tns-core-modules/ui/button/button.js', line: 26, column: 23

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Object_button_19_32_ClickListenerImpl.onClick(Object_button_19_32_ClickListenerImpl.java:12)
	at android.view.View.performClick(View.java:5205)
	at android.view.View$PerformClick.run(View.java:21164)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IllegalArgumentException: permission is null
	at android.support.v4.content.ContextCompat.checkSelfPermission(ContextCompat.java:450)
	... 16 more
</pre>

**Comment by NathanaelA** [comment]
Can you paste the code in that you are using to call hasPermission?

**Comment by psnehanshu** [comment]
I found the solution, I was trying to get permission for `android.Manifest.permission.FLASHLIGHT`, but then I realized that this permission was removed from Android. So now I'm using `android.Manifest.permission.CAMERA` which works fine.
